version: '3.8'

services:
  # Todo app -> React + Firebase App 
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_FIREBASE_API_KEY=${VITE_FIREBASE_API_KEY}
        - VITE_FIREBASE_AUTH_DOMAIN=${VITE_FIREBASE_AUTH_DOMAIN}
        - VITE_FIREBASE_PROJECT_ID=${VITE_FIREBASE_PROJECT_ID}
        - VITE_FIREBASE_STORAGE_BUCKET=${VITE_FIREBASE_STORAGE_BUCKET}
        - VITE_FIREBASE_MESSAGING_SENDER_ID=${VITE_FIREBASE_MESSAGING_SENDER_ID}
        - VITE_FIREBASE_APP_ID=${VITE_FIREBASE_APP_ID}
    container_name: react-firebase-app
    ports:
      - "80:80"
    restart: always
    volumes:
      - firebase-config:/usr/share/nginx/html/firebase-config
    networks:
      - app-network
    env_file:
      - .env

  dummy-db:
    image: mysql:8.0
    container_name: dummy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dummyroot
      MYSQL_DATABASE: dummydb
      MYSQL_USER: dummyuser
      MYSQL_PASSWORD: dummypassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  firebase-config:
    driver: local
  db-data:   
    driver: local

networks:
  app-network:
    driver: bridge
